import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";

/**
 * `codeceipt init` — the installer. Drops the two files a repo needs so the
 * verification runs for real in its own CI:
 *   .github/workflows/codeceipt.yml   the workflow that runs the Action on PRs
 *   codeceipt.yml                     a starter spec (acceptance criteria)
 *
 * It detects the package manager + test command so the generated workflow
 * actually installs deps and the spec's shell criterion runs the real suite.
 * Pure, side-effect-light, and `--dry-run`-able so it's unit-testable and safe.
 */

export type PackageManager = "pnpm" | "yarn" | "npm" | "bun";

export interface InitPlan {
  pm: PackageManager;
  /** Command the spec's shell criterion runs, e.g. "npm test". null = none found. */
  testCommand: string | null;
  /** Lockfile-driven install step for the workflow. null = skip (no lockfile). */
  install: string | null;
  /** True when a pnpm lockfile means we add pnpm/action-setup. */
  needsPnpmSetup: boolean;
  workflow: string;
  spec: string;
}

export interface InitFile {
  path: string;
  status: "written" | "skipped (exists)" | "would write" | "would skip (exists)";
}

export interface InitResult {
  plan: InitPlan;
  files: InitFile[];
}

const WORKFLOW_PATH = ".github/workflows/codeceipt.yml";
const SPEC_PATH = "codeceipt.yml";

function readJson(path: string): Record<string, unknown> | null {
  try {
    return JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
  } catch {
    return null;
  }
}

export function detectPackageManager(dir: string): PackageManager {
  if (existsSync(join(dir, "pnpm-lock.yaml"))) return "pnpm";
  if (existsSync(join(dir, "yarn.lock"))) return "yarn";
  if (existsSync(join(dir, "bun.lockb"))) return "bun";
  return "npm";
}

/** Resolve the test command from package.json scripts (null if there's none). */
export function detectTestCommand(dir: string, pm: PackageManager): string | null {
  const pkg = readJson(join(dir, "package.json"));
  const scripts = (pkg?.scripts ?? {}) as Record<string, string>;
  const test = scripts.test;
  // npm's default placeholder ("Error: no test specified") isn't a real suite.
  if (!test || /no test specified/i.test(test)) return null;
  return pm === "npm" ? "npm test" : `${pm} test`;
}

function detectInstall(dir: string, pm: PackageManager): string | null {
  if (pm === "pnpm" && existsSync(join(dir, "pnpm-lock.yaml"))) return "pnpm install --frozen-lockfile";
  if (pm === "yarn" && existsSync(join(dir, "yarn.lock"))) return "yarn install --frozen-lockfile";
  if (pm === "bun" && existsSync(join(dir, "bun.lockb"))) return "bun install --frozen-lockfile";
  if (pm === "npm" && existsSync(join(dir, "package-lock.json"))) return "npm ci";
  return null; // no lockfile → nothing reproducible to install
}

export function renderWorkflow(plan: Pick<InitPlan, "pm" | "install" | "needsPnpmSetup">): string {
  const steps: string[] = [
    "      - uses: actions/checkout@v4",
    "        with:",
    "          fetch-depth: 0   # full history so the PR diff can be computed",
  ];
  if (plan.needsPnpmSetup) steps.push("      - uses: pnpm/action-setup@v4");
  steps.push("      - uses: actions/setup-node@v4", '        with:', '          node-version: "20"');
  if (plan.install) steps.push(`      - run: ${plan.install}`);
  steps.push(
    "      - uses: Rejnyx/Codeceipt@v1",
    "        with:",
    '          fail-on-block: "true"   # block the merge when a blocking criterion fails',
  );

  return `# Generated by \`codeceipt init\`. Runs the verification in your own CI on
# every pull request and posts a public, re-runnable receipt.
name: Codeceipt
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
${steps.join("\n")}
`;
}

export function renderSpec(plan: Pick<InitPlan, "testCommand">): string {
  const testBlock = plan.testCommand
    ? `  - id: tests-pass
    kind: shell
    description: "The test suite passes (executed for real in CI)"
    command: "${plan.testCommand}"
    expect: exit_zero
    blocking: true
`
    : `  # No test script detected. Add one and uncomment to verify it runs:
  # - id: tests-pass
  #   kind: shell
  #   description: "The test suite passes"
  #   command: "npm test"
  #   expect: exit_zero
  #   blocking: true
`;

  return `# Codeceipt spec — the acceptance criteria this repo is verified against.
# Each criterion is checked by execution; the diff + the run are the evidence.
# Docs: https://codeceipt.dev   ·   edit these to match what you actually ship.
version: 1
criteria:
  - id: no-secrets
    kind: regex
    description: "No hardcoded secrets or API keys in the change"
    pattern: "(sk-[a-zA-Z0-9]{20,}|AIza[0-9A-Za-z_-]{35}|ghp_[0-9A-Za-z]{36})"
    expect: absent
    blocking: true

${testBlock}
  # --- More criteria you can turn on (delete the # to enable) ---
  #
  # - id: feature-present
  #   kind: regex
  #   description: "The change actually implements the thing it claims"
  #   pattern: "idempotenc"
  #   in: "src/handler.ts"
  #   blocking: true
  #
  # - id: ships-a-test
  #   kind: read_set
  #   description: "A new feature ships with a test that touches it"
  #   paths:
  #     - "src/handler.ts"
  #     - "test/handler.test.ts"
  #   blocking: false
  #
  # - id: migration-exists
  #   kind: file_predicate
  #   description: "A schema change includes a migration file"
  #   path: "migrations/"
  #   predicate: exists
  #   blocking: false
`;
}

export function planInit(dir: string): InitPlan {
  const pm = detectPackageManager(dir);
  const testCommand = detectTestCommand(dir, pm);
  const install = detectInstall(dir, pm);
  const needsPnpmSetup = pm === "pnpm" && Boolean(install);
  const workflow = renderWorkflow({ pm, install, needsPnpmSetup });
  const spec = renderSpec({ testCommand });
  return { pm, testCommand, install, needsPnpmSetup, workflow, spec };
}

export function runInit(dir: string, opts: { force?: boolean; dryRun?: boolean } = {}): InitResult {
  const plan = planInit(dir);
  const files: InitFile[] = [];

  for (const [rel, content] of [
    [WORKFLOW_PATH, plan.workflow],
    [SPEC_PATH, plan.spec],
  ] as const) {
    const abs = join(dir, rel);
    const exists = existsSync(abs);
    if (exists && !opts.force) {
      files.push({ path: rel, status: opts.dryRun ? "would skip (exists)" : "skipped (exists)" });
      continue;
    }
    if (!opts.dryRun) {
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, content, "utf8");
    }
    files.push({ path: rel, status: opts.dryRun ? "would write" : "written" });
  }

  return { plan, files };
}

/** Human-readable summary for the CLI. */
export function formatInitResult(res: InitResult): string {
  const { plan, files } = res;
  const lines = [
    "codeceipt init",
    "",
    `  package manager   ${plan.pm}`,
    `  test command      ${plan.testCommand ?? "none detected — spec has a commented placeholder"}`,
    `  install step      ${plan.install ?? "none (no lockfile)"}`,
    "",
    ...files.map((f) => `  ${f.status.startsWith("skip") || f.status.includes("skip") ? "·" : "+"} ${f.path}  (${f.status})`),
    "",
    "Next:",
    "  1. Review codeceipt.yml — make the criteria match what you ship.",
    "  2. git add codeceipt.yml .github/workflows/codeceipt.yml && git commit",
    "  3. Open a PR — Codeceipt verifies it by execution and posts a receipt.",
  ];
  return lines.join("\n");
}
