/* ============================================================
   Codeceipt — sample Receipt data
   Exposed as window.RECEIPTS  (keyed by id)
   ============================================================ */
(function () {
  const VERIFIED = {
    id: 'rcpt_a1f93c2e',
    fingerprint: 'cc1:8f3a2e9d4b7c1056',
    verdict: 'VERIFIED',
    summary: 'This pull request was independently executed in an isolated sandbox and met all 8 of 8 claimed criteria.',
    claimsMet: 8,
    claimsTotal: 8,
    pr: {
      platform: 'GitHub',
      repo: 'acme-pay/checkout-service',
      number: 482,
      title: 'Add idempotency keys to the payment webhook handler',
      author: 'devin-bot',
      authorKind: 'AI agent',
      branch: 'feat/webhook-idempotency',
      baseSha: 'a3c9f01',
      headSha: 'e7b2d48',
    },
    requestedBy: 'maya@northbeam.dev',
    issuedAt: '2026-05-30 14:22:07 UTC',
    issuedAtRel: 'verified 38 minutes ago',
    duration: '2m 41s',
    env: 'ubuntu-22.04 · node 20.11 · postgres 16',
    criteria: [
      { id: 1, label: 'Webhook handler rejects duplicate event IDs', status: 'pass',
        evidence: 'Replayed 3 identical Stripe events → 1 processed, 2 returned 200 with `already_processed`. No duplicate ledger rows.',
        cmd: 'pnpm test webhook/idempotency.spec.ts', out: '14 passed (14)' },
      { id: 2, label: 'Idempotency keys persisted to Postgres', status: 'pass',
        evidence: 'Row written to `webhook_events` with unique constraint on (provider, event_id). Verified via direct query post-run.',
        cmd: 'psql -c "select count(*) from webhook_events"', out: '3' },
      { id: 3, label: 'Replayed events do not double-charge', status: 'pass',
        evidence: 'Charge mock asserted called exactly once across 3 deliveries of the same event.',
        cmd: 'pnpm test billing/no-double-charge.spec.ts', out: '6 passed (6)' },
      { id: 4, label: 'Integration test for concurrent delivery added', status: 'pass',
        evidence: 'New test fires 10 concurrent identical webhooks; exactly one is processed under row lock.',
        cmd: 'pnpm test --grep "concurrent delivery"', out: '1 passed (1)' },
      { id: 5, label: 'Migration is reversible', status: 'pass',
        evidence: 'Ran up then down then up — schema diff is empty. No data loss on rollback.',
        cmd: 'pnpm migrate:up && pnpm migrate:down && pnpm migrate:up', out: 'OK · reversible' },
      { id: 6, label: 'No new type errors', status: 'pass',
        evidence: 'Full project typecheck clean against the PR head.',
        cmd: 'pnpm tsc --noEmit', out: '0 errors' },
      { id: 7, label: 'No new lint violations', status: 'pass',
        evidence: 'ESLint diff vs base shows 0 added problems.',
        cmd: 'pnpm lint --max-warnings 0', out: '0 problems' },
      { id: 8, label: 'P95 webhook latency stays under 120 ms', status: 'pass',
        evidence: 'Load test (500 req) measured P95 = 96 ms, within the stated 120 ms budget.',
        cmd: 'pnpm bench webhook --n 500', out: 'p95 96ms · p99 142ms' },
    ],
    diff: {
      files: 6, additions: 214, deletions: 23,
      sample: [
        { t: 'meta', s: 'src/webhooks/handler.ts' },
        { t: 'ctx',  s: '  export async function handleEvent(req: Request) {' },
        { t: 'ctx',  s: '    const event = parse(req);' },
        { t: 'add',  s: '    const seen = await db.webhookEvents.findUnique({' },
        { t: 'add',  s: '      where: { provider_eventId: { provider, eventId: event.id } },' },
        { t: 'add',  s: '    });' },
        { t: 'add',  s: '    if (seen) return ok({ status: "already_processed" });' },
        { t: 'ctx',  s: '    const result = await processCharge(event);' },
        { t: 'del',  s: '    return ok(result);' },
        { t: 'add',  s: '    await db.webhookEvents.create({ data: { provider, eventId: event.id } });' },
        { t: 'add',  s: '    return ok(result);' },
        { t: 'ctx',  s: '  }' },
      ],
    },
    cost: {
      compute: '2m 41s', cpu: 'sandbox · 4 vCPU',
      llmTokens: '184,920', llmModel: 'criteria extraction · gpt-class',
      usd: '0.038',
      breakdown: [
        { label: 'Clone + restore cache', v: '11s', usd: '0.001' },
        { label: 'Criteria extraction (LLM)', v: '184.9k tok', usd: '0.024' },
        { label: 'Deterministic execution', v: '2m 18s', usd: '0.012' },
        { label: 'Receipt build + sign', v: '12s', usd: '0.001' },
      ],
    },
  };

  const FAILED = {
    id: 'rcpt_4d20be77',
    fingerprint: 'cc1:b09c71fe23aa84d1',
    verdict: 'FAILED',
    summary: 'This pull request was independently executed and met 5 of 7 claimed criteria. Two claims could not be reproduced.',
    claimsMet: 5,
    claimsTotal: 7,
    pr: {
      platform: 'GitHub',
      repo: 'acme-pay/search-api',
      number: 119,
      title: 'Cache product search results in Redis',
      author: 'sweep-ai',
      authorKind: 'AI agent',
      branch: 'feat/search-cache',
      baseSha: '7712aab', headSha: '0c4e9f1',
    },
    requestedBy: 'lee@orbit.studio',
    issuedAt: '2026-05-29 09:08:51 UTC',
    issuedAtRel: 'verified yesterday',
    duration: '3m 12s',
    env: 'ubuntu-22.04 · node 20.11 · redis 7',
    criteria: [
      { id: 1, label: 'Search results cached in Redis', status: 'pass',
        evidence: 'Cache hit observed on second identical query; TTL set to 300s.', cmd: 'pnpm test cache.spec.ts', out: '8 passed (8)' },
      { id: 2, label: 'Cache invalidated on product update', status: 'fail',
        evidence: 'Updating a product left the stale entry in cache — assertion failed. Cache key not busted on write.',
        cmd: 'pnpm test invalidation.spec.ts', out: '1 failed, 2 passed' },
      { id: 3, label: 'Falls back to DB on Redis outage', status: 'pass',
        evidence: 'With Redis killed mid-test, query served from Postgres with no error.', cmd: 'pnpm test fallback.spec.ts', out: '4 passed (4)' },
      { id: 4, label: 'No new type errors', status: 'pass', evidence: 'Typecheck clean.', cmd: 'pnpm tsc --noEmit', out: '0 errors' },
      { id: 5, label: 'P95 latency improved vs baseline', status: 'pass',
        evidence: 'P95 dropped from 210ms to 74ms on warm cache.', cmd: 'pnpm bench search', out: 'p95 74ms' },
      { id: 6, label: 'Integration test for cache stampede', status: 'fail',
        evidence: 'Claimed test does not exist in the diff. No file matched the described stampede scenario.',
        cmd: 'pnpm test --grep "stampede"', out: '0 tests found' },
      { id: 7, label: 'No new lint violations', status: 'pass', evidence: 'ESLint diff clean.', cmd: 'pnpm lint', out: '0 problems' },
    ],
    diff: { files: 4, additions: 96, deletions: 12, sample: [
      { t: 'meta', s: 'src/search/cache.ts' },
      { t: 'add', s: '  const cached = await redis.get(key);' },
      { t: 'add', s: '  if (cached) return JSON.parse(cached);' },
      { t: 'ctx', s: '  const rows = await db.search(q);' },
      { t: 'add', s: '  await redis.set(key, JSON.stringify(rows), "EX", 300);' },
    ] },
    cost: { compute: '3m 12s', cpu: 'sandbox · 4 vCPU', llmTokens: '142,300', llmModel: 'criteria extraction · gpt-class', usd: '0.041',
      breakdown: [
        { label: 'Clone + restore cache', v: '14s', usd: '0.001' },
        { label: 'Criteria extraction (LLM)', v: '142.3k tok', usd: '0.019' },
        { label: 'Deterministic execution', v: '2m 44s', usd: '0.020' },
        { label: 'Receipt build + sign', v: '10s', usd: '0.001' },
      ] },
  };

  const PARTIAL = {
    id: 'rcpt_77c1aa90',
    fingerprint: 'cc1:5ad7c4901bb2e6f8',
    verdict: 'PARTIAL',
    summary: 'This pull request met 6 of 8 claimed criteria. Two could not be verified because they require a staging environment Codeceipt could not reach.',
    claimsMet: 6, claimsTotal: 8,
    pr: { platform: 'GitLab', repo: 'northbeam/billing-portal', number: 73,
      title: 'Add Stripe customer portal deep-link', author: 'm.okafor', authorKind: 'Human + AI assist',
      branch: 'feat/portal-link', baseSha: 'd91ee20', headSha: 'fa30c7b' },
    requestedBy: 'sam@northbeam.dev', issuedAt: '2026-05-30 11:47:00 UTC', issuedAtRel: 'verified 3 hours ago',
    duration: '1m 58s', env: 'ubuntu-22.04 · node 20.11',
    criteria: [
      { id: 1, label: 'Generates a valid portal session URL', status: 'pass', evidence: 'Mock Stripe returned a session; URL shape validated.', cmd: 'pnpm test portal.spec.ts', out: '5 passed (5)' },
      { id: 2, label: 'Requires authenticated session', status: 'pass', evidence: 'Anonymous request returns 401.', cmd: 'pnpm test auth.spec.ts', out: '3 passed (3)' },
      { id: 3, label: 'Handles Stripe API error gracefully', status: 'pass', evidence: 'Forced 500 → user sees retry, no crash.', cmd: 'pnpm test errors.spec.ts', out: '4 passed (4)' },
      { id: 4, label: 'No new type errors', status: 'pass', evidence: 'Typecheck clean.', cmd: 'pnpm tsc --noEmit', out: '0 errors' },
      { id: 5, label: 'No new lint violations', status: 'pass', evidence: 'Lint clean.', cmd: 'pnpm lint', out: '0 problems' },
      { id: 6, label: 'Unit coverage above 80%', status: 'pass', evidence: 'Coverage 84% on changed files.', cmd: 'pnpm test --coverage', out: '84.1%' },
      { id: 7, label: 'E2E click-through verified in staging', status: 'warn', evidence: 'Skipped — requires staging secrets not available to the sandbox. Cannot execute, so not certified.', cmd: 'playwright test e2e/portal', out: 'skipped (no env)' },
      { id: 8, label: 'Sentry breadcrumb on portal open', status: 'warn', evidence: 'Skipped — depends on live Sentry DSN. Not reproducible offline.', cmd: 'pnpm test sentry.spec.ts', out: 'skipped (no env)' },
    ],
    diff: { files: 3, additions: 71, deletions: 4, sample: [
      { t: 'meta', s: 'src/billing/portal.ts' },
      { t: 'add', s: '  const session = await stripe.billingPortal.sessions.create({' },
      { t: 'add', s: '    customer: customerId, return_url: returnUrl,' },
      { t: 'add', s: '  });' },
      { t: 'add', s: '  return session.url;' },
    ] },
    cost: { compute: '1m 58s', cpu: 'sandbox · 4 vCPU', llmTokens: '98,400', llmModel: 'criteria extraction · gpt-class', usd: '0.022',
      breakdown: [
        { label: 'Clone + restore cache', v: '9s', usd: '0.001' },
        { label: 'Criteria extraction (LLM)', v: '98.4k tok', usd: '0.013' },
        { label: 'Deterministic execution', v: '1m 38s', usd: '0.007' },
        { label: 'Receipt build + sign', v: '11s', usd: '0.001' },
      ] },
  };

  window.RECEIPTS = {
    [VERIFIED.id]: VERIFIED,
    [FAILED.id]: FAILED,
    [PARTIAL.id]: PARTIAL,
    _default: VERIFIED.id,
    _verified: VERIFIED.id,
    _failed: FAILED.id,
    _partial: PARTIAL.id,
  };

  // Loading steps for the execution flow
  window.LOADING_STEPS = [
    { key: 'clone',   label: 'Cloning repository', detail: 'git clone acme-pay/checkout-service @ e7b2d48', ms: 1100,
      logs: ['$ git clone --depth 1 …', 'Receiving objects: 100% (1284/1284)', 'restored pnpm store from cache (412 MB)'] },
    { key: 'parse',   label: 'Parsing claimed criteria', detail: 'extracting what the PR says it does', ms: 1300,
      logs: ['reading PR description + linked issue #471', 'found 8 verifiable claims', 'mapped 8/8 claims → executable checks'] },
    { key: 'exec',    label: 'Executing checks in sandbox', detail: 'deterministic run — not the agent\u2019s summary', ms: 2600,
      logs: ['installing deps … pnpm install --frozen-lockfile', 'spinning up postgres:16 + redis:7', '▶ pnpm test webhook/idempotency.spec.ts', '  14 passed (14)', '▶ pnpm test billing/no-double-charge.spec.ts', '  6 passed (6)', '▶ pnpm tsc --noEmit → 0 errors', '▶ pnpm bench webhook --n 500 → p95 96ms'] },
    { key: 'build',   label: 'Building & signing Receipt', detail: 'hash, timestamp, public URL', ms: 1100,
      logs: ['8/8 criteria reproduced', 'computing verification fingerprint', 'signed cc1:8f3a2e9d4b7c1056', 'Receipt published → codeceipt.dev/r/rcpt_a1f93c2e'] },
  ];
})();
